- mlx_steering_dump.py
Signed-off-by: Jiawei Wang <jiaweiw@mellanox.com>
> using json.load to speed up parser

- mlx_steering_dump_parser.py
- src/dr_domain.py
- src/dr_prettify.py
Split the parsing and printing logic.
Parse one domain at a time.
Signed-off-by: Daria Velikovsky <daria@mellanox.com>
> dump_parser refactoring

- mlx_steering_dump_parser.py
- src/dr_trigger.py
Add one arg -flowptr for the rte_flow_ptr and user query single rule info by it.
Construct flowptr in iovec.
Signed-off-by: Haifei Luo <haifeil@nvidia.com>
> Add support for single flow dump feature

- internal_tools/ste_dumper.sh
- internal_tools/ste_dumper_python.py
Add new tool to support icm memory single index dump.
Usage: ./ste_dumper.sh -h
> Add new tool "ste_dumper'

- src/dr_prettify.py
Fix the condition that checks if STE tag includes src/dst ip field
in order to pretify it(print it in xx.xx.xx.xx format).
> Fix ip address prettify condition

- src/dr_trigger.py
Fixes: 774d1fd28268 ("Add support for single flow dump feature")
> Fix mixed spaces and tabs error in dr_trigger.py

- src/dr_trigger.py
The data structure sent to the application should be packed
and endianness must be specified. Native host endianness can
be used, all exchange happens within the same host (we
use sendmsg aux data and share the file handle, so remote
approach is not applicable, no inter-host communication
happens).
The message structure to dump one/all flow(s):
struct mlx5_flow_dump_reg {
uint32_t port_id;  // there are plans in DPDK to extend port_id
uint64_t flow_ptr;
} __rte_pack;
If flow_ptr is 0, all flows will be dumped. Previous DPDK
version did not check the message size, there should be no
compatibility issue.
Signed-off-by: Viacheslav Ovsiienko <viacheslavo@nvidia.com>
> Fix support for single flow dump feature

- src/parsers/mlx5_ifc_parser.py
modify hdr can have several actions. The parserd hdr string
should be accumulated.
Signed-off-by: Haifei Luo <haifeil@nvidia.com>
> src/parsers: modify hdr string should be accumulated

- src/dr_action.py
- src/dr_rule.py
- src/dr_table.py
- src/parsers/mlx5_ifc_parser.py
For example:
table 0x5b499a0, type FDB, ufid 0x5bf96d0   key: in_port: sf0     action: METER & MODIFY_HDR(hdr(set_reg_c3=0x8000)) & JUMP to Next Table 0x5bf1080
table 0x5bdca00, type FDB, ufid 0x5bfaec0   key: in_port: sf0    action: MODIFY_HDR(hdr(set_reg_c2=0xf0000)) & counter(hits(704), bytes(119944)) & JUMP to Next Table 0x5bf9730
table 0x5bdcc60, type FDB, ufid 0x5bf6f00   key: metadata_reg_c_3: 0x00008000 metadata_reg_c_3: 0x00008000    action: counter(hits(0), bytes(0)) & DROP
table 0x5bdcc60, type FDB, ufid 0x5bee670   key: metadata_reg_c_3: 0x00000100 metadata_reg_c_3: 0x00000100    action: counter(hits(0), bytes(0)) & DROP
table 0x5bdcc60, type FDB, ufid 0x5bed3b0   key:      action: DROP
table 0x5bdf720, type FDB, ufid 0x5be0bc0   key: metadata_reg_c_3: 0x00000002 …
> Hw jump and modify

- src/parsers/dr_ste_v1_tag_parser.py
Signed-off-by: Slava Shwartsman <slavash@nvidia.com>
> Add spport for definer 35 and 36

- internal_tools/ste_dumper.sh
> internal_tools: add new resource types to dump

- hw_steering_src/dr_hl.py
> HWS: Fixes in HL offsets calculations

- hw_steering_src/dr_common.py
- hw_steering_src/dr_matcher.py
Remove table id from matcher output
> HWS: Remove table id from matcher output

- hws/src/dr_context.py
- hws/src/dr_dump_hw.py
- hws/src/dr_matcher.py
- hws/src/dr_table.py
Support resource sharing feature, add the ability
to dump the resources from the shared device.
> HWS: Support resource sharing feature

- src/dr_domain.py
Add domain's flags, and buddies statistics that are currently in use for that domain.
STE-buddies, modify-header-buddies and pattern-buddies.
Signed-off-by: Erez Shitrit <erezsh@nvidia.com>
> SW: Add more details to domain dump

- hws/src/dr_action.py
Set capital letter, reduce modify action list string.
> HWS: Improve action names

- hws/src/dr_action.py
- hws/src/dr_common.py
- hws/src/dr_common_functions.py
- hws/src/dr_hw_resources.py
Add the necessary fields and functions to parse the add_field action.
This patch also fixes a bug in copy action source parse.
> HWS: Support ADD_FIELD action

- hws/src/dr_hw_resources.py
Fix raw modify header representation by adding missing prefix zeros.
> HWS: Fix raw modify header representation

- hws/src/dr_action.py
- hws/src/dr_common.py
Support PSP encryption/decryption action parsing.
> HWS: Support PSP encryption/decryption action

- hws/src/dr_rule.py
Give correct STE table type hints for FDB_RX, FDB_TX and unified.
> HWS: Give correct STE table type hints

- hws/README.md
- hws/mlx_hw_steering_parser.py
- hws/src/dr_common_functions.py
- hws/src/dr_remote.py
Support dumping HW resources from remote setup device by specifying remote setup IP, use -h flag for more info.
> HWS: Support dumping HW resources from remote
